### ISSUE TITLE
Add angle unit

### ISSUE THREAD

**Issue by mkamyab** [sbyrnes321/numericalunits#13]
I'm wondering if there is any plan for adding angle as a unit of a quantity and be able to convert degree to radian?

**Comment by sbyrnes321** [comment]
No, because then you need to start doing unintuitive things like redefining angle-related functions

    def my_cosine(θ): return math.cos(θ/radian)
    def my_arcsine(x): return math.asin(x) * radian

and putting angles in lots of other unexpected places too.

That said, I have actually done this plenty of times, and you can too, it's not hard. But I think it would be annoying and confusing for most people.

[Further discussion](https://physics.stackexchange.com/a/368877)
