### ISSUE TITLE
Add rpm definition

### ISSUE THREAD

**Issue by jonas-** [sbyrnes321/numericalunits#5]
Hi

I like your package and it would be great if you could add the definition for rpm (rounds per minute):

`rpm = 2*pi/minute`

Thanks, 
Jonas

**Comment by sbyrnes321** [comment]
Thanks for the suggestion! The new version 1.21 now has rpm, but for consistency (e.g. we better have 60rpm=1Hz!), I defined it as rpm = 1/minute (1 cycle per minute). If you want to keep track of radians instead of cycles, I defined the variable rpm·2π for the quantity you suggested, i.e. 2pi/minute. (Because of the unicode · character, the rpm·2π variable only works if you are using Python 3, not Python 2.)
